# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlateaGEE
                                 A QGIS plugin
 PlateaGIS_ndvi_ndmi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-05
        copyright            : (C) 2023 by ryali93/tidop
        email                : roy.yali@usal.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PlateaGEE class from file PlateaGEE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PlateaGEE import PlateaGEE
    return PlateaGEE(iface)
