# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlateaGEE
                                 A QGIS plugin
 PlateaGIS_ndvi_ndmi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-05
        git sha              : $Format:%H$
        copyright            : (C) 2023 by ryali93/tidop
        email                : roy.yali@usal.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# from PyQt5 import QtWebEngineWidgets  # Esto debe estar al principio
from qgis.gui import QgsMapToolEmitPoint
from qgis.core import QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsProject
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QDate, QUrl
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QLineEdit, QMessageBox, QPushButton, QVBoxLayout

# import plotly.graph_objs as go
# from PyQt5.QtWebEngineWidgets import QWebEngineView
# from PyQt5.QtWebKitWidgets import QWebView

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .PlateaGEE_dialog import PlateaGEEDialog
import os.path
import json
import requests
from datetime import datetime

from .ee_utils import *

from qgis.gui import QgsMapToolEmitPoint
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsRectangle
from qgis.gui import QgsRubberBand
from qgis.core import QgsWkbTypes
from qgis.PyQt.QtGui import QColor
from qgis.core import QgsPointXY
from qgis.core import QgsVectorLayer, QgsFeature, QgsGeometry

from matplotlib.dates import DateFormatter
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class RectangleMapTool(QgsMapToolEmitPoint):
    rectangleSelected = pyqtSignal(QgsRectangle)

    def __init__(self, canvas):
        self.canvas = canvas
        QgsMapToolEmitPoint.__init__(self, self.canvas)
        self.rubberBand = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
        self.rubberBand.setColor(QColor(255, 0, 0, 100))
        self.rubberBand.setWidth(1)
        self.reset()

    def reset(self):
        self.startPoint = self.endPoint = None
        self.isEmittingPoint = False
        self.rubberBand.reset(QgsWkbTypes.PolygonGeometry)

    def canvasPressEvent(self, e):
        self.startPoint = self.toMapCoordinates(e.pos())
        self.endPoint = self.startPoint
        self.isEmittingPoint = True
        self.showRect(self.startPoint, self.endPoint)

    def canvasReleaseEvent(self, e):
        self.isEmittingPoint = False
        r = self.rectangle()
        if r is not None:
            self.rectangleSelected.emit(r)
        self.reset()

    def canvasMoveEvent(self, e):
        if not self.isEmittingPoint:
            return

        self.endPoint = self.toMapCoordinates(e.pos())
        self.showRect(self.startPoint, self.endPoint)

    def showRect(self, startPoint, endPoint):
        self.rubberBand.reset(QgsWkbTypes.PolygonGeometry)
        if startPoint.x() == endPoint.x() or startPoint.y() == endPoint.y():
            return

        point1 = QgsPointXY(startPoint.x(), startPoint.y())
        point2 = QgsPointXY(startPoint.x(), endPoint.y())
        point3 = QgsPointXY(endPoint.x(), endPoint.y())
        point4 = QgsPointXY(endPoint.x(), startPoint.y())

        self.rubberBand.addPoint(point1, False)
        self.rubberBand.addPoint(point2, False)
        self.rubberBand.addPoint(point3, False)
        self.rubberBand.addPoint(point4, True)
        self.rubberBand.show()

    def rectangle(self):
        if self.startPoint is None or self.endPoint is None:
            return None
        elif self.startPoint.x() == self.endPoint.x() or self.startPoint.y() == self.endPoint.y():
            return None

        return QgsRectangle(self.startPoint, self.endPoint)


class PlateaGEE:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'PlateaGEE_{}.qm'.format(locale))

        self.creds = get_credentials("https://ryali93.users.earthengine.app/view/plateaapi") # "https://ryali93.users.earthengine.app/view/plateaapi"

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&PlateaGEE')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # Define a rectangle layer to be used for the selection
        self.rectangle_layer = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('PlateaGEE', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/PlateaGEE/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'PlateaGEE'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.dockwidget = PlateaGEEDialog()
        # Conectar los campos de entrada con los atributos de la instancia del complemento
        self.dockwidget.lon_input = self.dockwidget.findChild(QLineEdit, 'lon_input')
        self.dockwidget.lat_input = self.dockwidget.findChild(QLineEdit, 'lat_input')
        self.dockwidget.start_date_input = self.dockwidget.findChild(QLineEdit, 'start_date_input')
        self.dockwidget.end_date_input = self.dockwidget.findChild(QLineEdit, 'end_date_input')

        # Establecer la fecha de inicio y fin
        current_date = QDate.currentDate()
        start_date = current_date.addDays(-10)
        self.dockwidget.end_date_edit.setDate(current_date)
        self.dockwidget.start_date_edit.setDate(start_date)

         # Establecer el formato de visualización de las fechas
        date_display_format = "dd/MM/yyyy"
        self.dockwidget.start_date_edit.setDisplayFormat(date_display_format)
        self.dockwidget.end_date_edit.setDisplayFormat(date_display_format)

        # Conectar la señal accepted del button_box con el método on_button_box_accepted
        self.dockwidget.ok_button.clicked.connect(self.on_ok_button_clicked)
        self.dockwidget.back_button.clicked.connect(self.on_back_button_clicked)

        # Conectar la señal clicked del botón con el método on_select_point_button_clicked
        self.dockwidget.select_point_button.clicked.connect(self.on_select_point_button_clicked)

        # Conectar la señal clicked del botón con el método on_select_rectangle_button_clicked
        self.dockwidget.select_rectangle_button.clicked.connect(self.on_select_rectangle_button_clicked)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&PlateaGEE'),
                action)
            self.iface.removeToolBarIcon(action)

    # def create_plot(self, data):
    #         # Extraer las listas de tiempo, NDVI y NDMI
    #         time = [entry['time'] for entry in data]
    #         ndvi = [entry['NDVI'] for entry in data]
    #         ndmi = [entry['NDMI'] for entry in data]

    #         # Crear el gráfico con Plotly
    #         fig = go.Figure()
    #         fig.add_trace(go.Scatter(x=time, y=ndvi, mode='lines+markers', name='NDVI'))
    #         fig.add_trace(go.Scatter(x=time, y=ndmi, mode='lines+markers', name='NDMI'))
    #         fig.update_layout(title='NDVI y NDMI a lo largo del tiempo')

    #         # Convertir el gráfico de Plotly en una página HTML
    #         plot_html = fig.to_html(full_html=False)

    #         # Crear un QWebView para mostrar el gráfico de Plotly en el plugin
    #         plot_view = QWebView(self.dockwidget.plot_widget)
    #         plot_view.setHtml(plot_html)
    #         plot_view.setGeometry(0, 0, self.dockwidget.plot_widget.geometry().width(), self.dockwidget.plot_widget.geometry().height())
    #         plot_view.show()

    def clear_layout(self, layout):
        """ Elimina todos los widgets del layout dado. """
        if layout is not None:
            while layout.count():
                child = layout.takeAt(0)
                widget = child.widget()
                if widget:
                    widget.deleteLater()
    
    def create_plot(self, data):
        # Extraer las listas de tiempo, NDVI y NDMI
        time = [entry['time'] for entry in data]
        ndvi = [entry['NDVI'] for entry in data]
        ndmi = [entry['NDMI'] for entry in data]

        time = [datetime.strptime(d, '%Y-%m-%d') for d in time]


        # Crear el gráfico con Matplotlib
        plt.rc('font', family='serif')
        fig = Figure(figsize=(5, 4), dpi=100)
        ax = fig.add_subplot(111)
        ax.plot(time, ndvi, marker='o', label='NDVI')
        ax.plot(time, ndmi, marker='o', label='NDMI')
        ax.set_title('NDVI y NDMI')
        ax.set_ylim([-0.2, 1])
        # ax.xaxis.set_major_formatter(date_form)
        # ax.set_xticklabels(ax.get_xticks(), rotation = 30)
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
        fig.autofmt_xdate()
        ax.legend()
        
        print("Plot created")

        # Crear un FigureCanvasQTAgg para mostrar el gráfico de Matplotlib en el plugin
        plot_canvas = FigureCanvas(fig)

        # Si ya existe un layout, elimínalo
        layout = self.dockwidget.plot_widget.layout()
        if layout is None:
            layout = QVBoxLayout(self.dockwidget.plot_widget)
            self.dockwidget.plot_widget.setLayout(layout)
        else:
            self.clear_layout(layout)
        
        # Crea un nuevo layout y añade el gráfico
        layout.addWidget(plot_canvas)
        print("Plot added to layout")


    def on_ok_button_clicked(self):
        # Leemos las coordenadas y fechas desde los campos en el formulario
        lon_text = self.dockwidget.lon_input.text()
        lat_text = self.dockwidget.lat_input.text()

        start_date = self.dockwidget.start_date_edit.date().toString("yyyy-MM-dd")
        end_date = self.dockwidget.end_date_edit.date().toString("yyyy-MM-dd")

        if not lon_text or not lat_text:
            QMessageBox.critical(None, "Error", "Por favor, ingrese valores de longitud y latitud.")
            return

        lon = float(lon_text)
        lat = float(lat_text)

        # URL de la API (reemplaza con la dirección de tu API)
        url = f"http://localhost:5000/get_ndvi_ndmi_series?lon={lon}&lat={lat}&start_date={start_date}&end_date={end_date}"

        # Enviamos la solicitud a la API y obtenemos la respuesta
        response = requests.get(url)
        if response.status_code == 200:
            data = json.loads(response.text)
            # Muestra los resultados en un cuadro de mensaje
            msg = QMessageBox()
            msg.setWindowTitle("Resultados")
            msg.setText(json.dumps(data, indent=2))
            msg.exec_()
        else:
            # Muestra un mensaje de error si algo sale mal
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setWindowTitle("Error")
            msg.setText(f"Error al obtener datos de la API: {response.status_code}")
            msg.exec_()
        
        self.create_plot(data)

        # Ocultar campos de entrada y mostrar el gráfico
        self.dockwidget.lon_label.hide()
        self.dockwidget.lat_label.hide()
        self.dockwidget.start_date_label.hide()
        self.dockwidget.end_date_label.hide()
        self.dockwidget.lon_input.hide()
        self.dockwidget.lat_input.hide()
        self.dockwidget.start_date_edit.hide()
        self.dockwidget.end_date_edit.hide()
        self.dockwidget.ok_button.hide()
        self.dockwidget.plot_widget.show()
        self.dockwidget.back_button.show()
    
    def on_back_button_clicked(self):
        self.dockwidget.plot_widget.hide()
        self.dockwidget.lon_label.show()
        self.dockwidget.lat_label.show()
        self.dockwidget.start_date_label.show()
        self.dockwidget.end_date_label.show()
        self.dockwidget.lon_input.show()
        self.dockwidget.lat_input.show()
        self.dockwidget.start_date_edit.show()
        self.dockwidget.end_date_edit.show()
        self.dockwidget.ok_button.show()
    
    def on_polygon_button_clicked(self, layer):
        # Obtener la capa temporal
        start_date = self.dockwidget.start_date_edit.date().toString("yyyy-MM-dd")
        end_date = self.dockwidget.end_date_edit.date().toString("yyyy-MM-dd")

        # Extraer las coordenadas del rectángulo
        lon_min = layer.extent().xMinimum()
        lat_min = layer.extent().yMinimum()
        lon_max = layer.extent().xMaximum()
        lat_max = layer.extent().yMaximum()
        
        # Construir la URL para la solicitud GET
        # url = f'http://localhost:5000/get_ndvi_ndmi_polygon?lon_min={lon_min}&lat_min={lat_min}&lon_max={lon_max}&lat_max={lat_max}&start_date={start_date}&end_date={end_date}'

        # # Hacer la solicitud GET y parsear la respuesta JSON
        # response = requests.get(url)
        # if response.status_code == 200:
        #     data = json.loads(response.text)
        #     # Muestra los resultados en un cuadro de mensaje
        #     msg = QMessageBox()
        #     msg.setWindowTitle("Resultados")
        #     msg.setText(json.dumps(data, indent=2))
        #     msg.exec_()
        # else:
        #     # Muestra un mensaje de error si algo sale mal
        #     msg = QMessageBox()
        #     msg.setIcon(QMessageBox.Critical)
        #     msg.setWindowTitle("Error")
        #     msg.setText(f"Error al obtener datos de la API: {response.status_code}")
        #     msg.exec_()

        expression = create_query_ndvi_ndmi(lon_min, lat_min, lon_max, lat_max, start_date, end_date)
        data = get_data(self.creds, expression)
        data = data_to_json(data)

        self.create_plot(data)

        # Ocultar campos de entrada y mostrar el gráfico
        self.dockwidget.lon_label.hide()
        self.dockwidget.lat_label.hide()
        self.dockwidget.start_date_label.hide()
        self.dockwidget.end_date_label.hide()
        self.dockwidget.lon_input.hide()
        self.dockwidget.lat_input.hide()
        self.dockwidget.start_date_edit.hide()
        self.dockwidget.end_date_edit.hide()
        self.dockwidget.ok_button.hide()
        self.dockwidget.plot_widget.show()
        self.dockwidget.back_button.show()
    

    def transform_rectangle(self, rectangle):
        # Crear objetos CRS para los sistemas de coordenadas de origen y destino
        source_crs = QgsCoordinateReferenceSystem(25830)
        dest_crs = QgsCoordinateReferenceSystem(4326)

        # Crear una transformación de coordenadas
        transform = QgsCoordinateTransform(source_crs, dest_crs, QgsProject.instance())

        # Transformar las coordenadas
        rectangle = transform.transformBoundingBox(rectangle)

        # Devolver el rectángulo transformado
        return rectangle

    def on_select_rectangle_button_clicked(self):
        # Crear la herramienta de selección de rectángulo
        self.rectangle_tool = RectangleMapTool(self.iface.mapCanvas())

        # Conectar la señal rectangleSelected a una función que maneje el rectángulo seleccionado
        self.rectangle_tool.rectangleSelected.connect(self.on_rectangle_selected)

        # Activar la herramienta de selección de rectángulo
        self.iface.mapCanvas().setMapTool(self.rectangle_tool)

    def on_rectangle_selected(self, rectangle):
        # Transformar el rectángulo de EPSG:25830 a EPSG:4326
        rectangle = self.transform_rectangle(rectangle)

        # Si ya existe una capa, eliminarla
        if self.rectangle_layer is not None:
            QgsProject.instance().removeMapLayer(self.rectangle_layer)

        # Crear una capa en memoria para almacenar el rectángulo
        layer = QgsVectorLayer('Polygon?crs=epsg:4326', 'selected_rectangle', 'memory')

        # set transparency
        layer.setOpacity(0.5)
        
        # Crear un objeto QgsFeature y asignarle una geometría de polígono a partir del rectángulo
        feature = QgsFeature()
        feature.setGeometry(QgsGeometry.fromRect(rectangle))

        # Añadir el objeto QgsFeature a la capa
        layer.dataProvider().addFeatures([feature])

        # Añadir la capa al mapa
        QgsProject.instance().addMapLayer(layer)

        # Almacenar la referencia a la capa
        self.rectangle_layer = layer

        # Hacer algo con las coordenadas (por ejemplo, imprimirlas en la consola)
        self.on_polygon_button_clicked(layer=layer)

        # Desactivar la herramienta de selección de rectángulo
        self.iface.mapCanvas().unsetMapTool(self.rectangle_tool)

    def canvasClicked(self, point, button):
        source_crs = QgsCoordinateReferenceSystem("EPSG:25830")
        dest_crs = QgsCoordinateReferenceSystem("EPSG:4326")

        # Crear un objeto QgsCoordinateTransform utilizando los CRS
        transform = QgsCoordinateTransform(source_crs, dest_crs, QgsProject.instance())

        # Transformar el punto
        transformed_point = transform.transform(point)

        # Establecer las coordenadas transformadas en los campos de entrada
        self.dockwidget.lon_input.setText(str(round(transformed_point.x(), 4)))
        self.dockwidget.lat_input.setText(str(round(transformed_point.y(), 4)))

        # Desactivar la herramienta de selección de puntos
        self.iface.mapCanvas().unsetMapTool(self.select_point_tool)
    
    def on_select_point_button_clicked(self):
        self.select_point_tool = QgsMapToolEmitPoint(self.iface.mapCanvas())
        self.iface.mapCanvas().setMapTool(self.select_point_tool)
        self.select_point_tool.canvasClicked.connect(self.canvasClicked)

    def run(self):
        self.dockwidget.show()
